version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - doxygen docs/Doxyfile

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
